In [1]:
import numpy as np

In [43]:
S = np.array([[1,5,4,3,2],[2,1,5,4,3],[3,2,1,5,4],[4,3,2,1,5],[5,4,3,2,1]])
# np.linalg.inv(S)*75
S

array([[1, 5, 4, 3, 2],
       [2, 1, 5, 4, 3],
       [3, 2, 1, 5, 4],
       [4, 3, 2, 1, 5],
       [5, 4, 3, 2, 1]])

In [30]:
n = 5
# S = np.array()
# S
S = np.array([[((n+x-i) % n) + 1 for i in range(1,n+1)] for x in range(1,n+1)])
np.linalg.inv(S)*3*5*5 # 75

array([[-14.,   1.,   1.,   1.,  16.],
       [ 16., -14.,   1.,   1.,   1.],
       [  1.,  16., -14.,   1.,   1.],
       [  1.,   1.,  16., -14.,   1.],
       [  1.,   1.,   1.,  16., -14.]])

In [41]:
n = 6
S = np.array([[((n+x-i) % n) + 1 for i in range(1,n+1)] for x in range(1,n+1)])
# np.linalg.inv(S)*6*7*3 # 126
B = [81,75,75,93,93,87]
np.linalg.inv(S) @ B

array([5., 5., 4., 1., 4., 5.])

In [42]:
n = 10000
S = np.array([[((n+x-i) % n) + 1 for i in range(1,n+1)] for x in range(1,n+1)])
np.linalg.inv(S)*2*7*7*2# 196

array([[-1.95999996e-02,  3.91960805e-10,  3.91960802e-10, ...,
         3.91960804e-10,  3.91960804e-10,  1.96000004e-02],
       [ 1.96000004e-02, -1.95999996e-02,  3.91960802e-10, ...,
         3.91960804e-10,  3.91960804e-10,  3.91960804e-10],
       [ 3.91960804e-10,  1.96000004e-02, -1.95999996e-02, ...,
         3.91960804e-10,  3.91960804e-10,  3.91960804e-10],
       ...,
       [ 3.91960803e-10,  3.91960806e-10,  3.91960806e-10, ...,
        -1.95999996e-02,  3.91961020e-10,  3.91960857e-10],
       [ 3.91960806e-10,  3.91960803e-10,  3.91960803e-10, ...,
         1.96000004e-02, -1.95999996e-02,  3.91960488e-10],
       [ 3.91960803e-10,  3.91960806e-10,  3.91960803e-10, ...,
         3.91960804e-10,  1.96000004e-02, -1.95999996e-02]])

array([[-183.75,    5.25,    5.25,    5.25,    5.25,    5.25,    5.25,
         194.25],
       [ 194.25, -183.75,    5.25,    5.25,    5.25,    5.25,    5.25,
           5.25],
       [   5.25,  194.25, -183.75,    5.25,    5.25,    5.25,    5.25,
           5.25],
       [   5.25,    5.25,  194.25, -183.75,    5.25,    5.25,    5.25,
           5.25],
       [   5.25,    5.25,    5.25,  194.25, -183.75,    5.25,    5.25,
           5.25],
       [   5.25,    5.25,    5.25,    5.25,  194.25, -183.75,    5.25,
           5.25],
       [   5.25,    5.25,    5.25,    5.25,    5.25,  194.25, -183.75,
           5.25],
       [   5.25,    5.25,    5.25,    5.25,    5.25,    5.25,  194.25,
        -183.75]])

In [39]:
S

array([[1, 8, 7, 6, 5, 4, 3, 2],
       [2, 1, 8, 7, 6, 5, 4, 3],
       [3, 2, 1, 8, 7, 6, 5, 4],
       [4, 3, 2, 1, 8, 7, 6, 5],
       [5, 4, 3, 2, 1, 8, 7, 6],
       [6, 5, 4, 3, 2, 1, 8, 7],
       [7, 6, 5, 4, 3, 2, 1, 8],
       [8, 7, 6, 5, 4, 3, 2, 1]])